apiVersion: v1
kind: Service
metadata:
  name: playwright-service
spec:
  selector:
    app: playwright
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 55653  # Target port for Allure test report
  type: NodePort
